### ISSUE TITLE
语法错误

### ISSUE THREAD

**Issue by aheig** [hiCasper/Shell#13]
`
./AutoReinstall.sh: line 7: syntax error near unexpected token `newline'
./AutoReinstall.sh: line 7: `<!DOCTYPE html>'`

**Comment by aheig** [comment]
···
root@2021091762944:~# ./AutoReinstall.sh
./AutoReinstall.sh: line 7: syntax error near unexpected token `newline'
./AutoReinstall.sh: line 7: `<!DOCTYPE html>'
···

**Comment by aheig** [comment]
`root@2021091762944:~# ./AutoReinstall.sh
./AutoReinstall.sh: line 7: syntax error near unexpected token `newline'
./AutoReinstall.sh: line 7: `<!DOCTYPE html>'`

**Comment by C018** [comment]
raw获取真实链接就可以用

**Comment by aheig** [comment]
啊哈哈哈哈哈！！！犯了个低级错误！！
